# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='Title',
            new_name='title',
        ),
    ]
